spring:
  main:
    allow-bean-definition-overriding: false
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpa-remind1;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace